DROP TABLE IF EXISTS sale_products;
DROP TABLE IF EXISTS sales;
DROP TABLE IF EXISTS products;

CREATE TABLE products (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(255) NOT NULL,
                          entry_date DATE NOT NULL,
                          manufacturer VARCHAR(255) NOT NULL,
                          amount_in_stock INTEGER NOT NULL,
                          price NUMERIC(19, 2) NOT NULL
);

CREATE TABLE sales (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       invoice_id VARCHAR(255) NOT NULL UNIQUE,
                       customer VARCHAR(255),
                       date DATE,
                       status VARCHAR(255),
                       total_value INTEGER
);

CREATE TABLE sale_products (
                               sale_id BIGINT NOT NULL,
                               product_id BIGINT NOT NULL,
                               PRIMARY KEY (sale_id, product_id),
                               FOREIGN KEY (sale_id) REFERENCES sales(id),
                               FOREIGN KEY (product_id) REFERENCES products(id)
);
